# Generated by Django 3.0.5 on 2020-07-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='time',
            new_name='datetime',
        ),
        migrations.AlterField(
            model_name='history',
            name='message',
            field=models.CharField(max_length=120),
        ),
    ]
